# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY items_consumer.py .

# Install any needed packages specified in requirements.txt
RUN pip install pika requests

# Run notifications_consumer.py when the container launches
CMD ["python3", "items_consumer.py"]